### ISSUE TITLE
Removing our copyright is FORBIDDEN

### ISSUE THREAD

**Issue by d00p** [markc/netserva#1]
You removed all of our copyright notes from the sources, this is forbidden by the used license.

**Comment by guruevi** [comment]
@markc: You cannot remove copyright labels AT ALL whenever you 'release' the code. Putting it on github, is considered releasing the code. What you do in your private copy is up to you, but when you distribute it, regardless of it's state, you are required to respect the license.

Also, you can't just interchange between GPL2 and AGPL3 on the edits you make. You are writing a derivative therefore you need to stick to the license. If you write (in a clean room) from the ground up, you can do so in whatever license you want. This doesn't necessarily apply for stand-alone modules, however if you modify the 'core' functionality, you need to do so under the original GPL license unless you get permission from ALL the contributors on the source project.

Copyright notices are required on all files in a project (either in full or abbreviated), it doesn't impact the code generation/compilation, if you use a proper editor you could just hide them.

**Comment by markc** [comment]
This is a dead issue now but a vague question remains as to when is a derivative work no longer considered the original because it has been changed so much that the original code is no longer recognisable?

That was what I was aiming for at the time and part of the work in progress was to use `php -w` which strips ALL comments and whitespace and then I used `php-cs-fixer` to turn that mess back into editable code as well as various other scripted sed adjustments. At some point in the future I intended to put back the appropriate licenses according to my judgement as to whether the remaining code deserved the original license or was changed **enough** to be considered a new work that I would be free to re-license as I see fit. Manually tweaking the files with an editor was not part of the plan at that stage of the refactoring process. I'm not aware of any precedent to guide me as to when an individual file or a whole project is so massively changed that it no longer considered the original file or project.
